import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const parts=JSON.parse(read('src/parts.json'));
const records=JSON.parse(read('data/aircraft.json'));
for(const [type,r] of Object.entries(records)){
 assert(r.model&&r.performance&&r.tree&&r.ammo&&r.researchCost,'Incomplete aircraft: '+type);
 assert(fs.existsSync(path.join(root,'app/src/main/assets',r.model.modelFile)),'Missing model: '+type);
 for(const [id,w] of Object.entries(r.weapons))assert(w.cost>0&&w.count>0&&r.ammo[id]>0,'Invalid weapon: '+type+'/'+id);
}
const generated='\n// Generated by scripts/build-source.mjs. Edit src/ and data/aircraft.json.\n'+
 'const AIRCRAFT_DATA='+JSON.stringify(records,null,2)+';\n'+
 parts.map(part=>'\n// Source: src/'+part+'\n'+read('src/'+part)).join('\n');
let html=read('src/index.html');
assert(html.includes('<!-- STYLES -->')&&html.includes('<!-- GAME -->'),'Missing build placeholders');
html=html.replace('<!-- STYLES -->',()=>read('src/styles.css').trim()).replace('<!-- GAME -->',()=>generated.trim());
// Keep the embedded module byte-for-byte identical to the reviewable generated file.
const module=html.split('<script type="module">')[1].split('</script>')[0];
const outputs={'game.mjs':module,'app/src/main/assets/index.html':html};
const check=process.argv.includes('--check');
for(const [file,content] of Object.entries(outputs)){
 if(check)assert.equal(read(file),content,file+' is stale; run npm run build:source');
 else fs.writeFileSync(path.join(root,file),content);
}
console.log(check?'Generated source is current.':'Built source from '+parts.length+' parts and '+Object.keys(records).length+' aircraft records.');
