import fs from 'node:fs';import assert from 'node:assert/strict';import {THREE,makeContext,info,plane,setDirection,playerStep,propStep} from './runtime.mjs';
const report={result:'passed',checks:[],cadence:[],flight:[]};
for(const fps of [30,60,120]){
 const h=makeContext(1);h.ctx.player=plane(h,'i16');h.ctx.playerPlane='i16';h.ctx.weaponMode='mg';h.ctx.playGunShot=()=>{};h.run("playerAmmo=freshAmmo('i16');playerWeaponCooldowns={mg:0,m2:0,mg762:0,n37:0,ns23:0,hispano:0}");
 for(let n=0;n<fps*2;n++)h.run(`fireWeapons(player,false,${1/fps},true)`);
 const spent=h.run('850-playerAmmo.mg');assert(Math.abs(spent-120)<=2);assert.equal(spent%2,0);assert(h.run('bullets.every(b=>b.speed===82.5&&b.damage===16)'));
 h.run('playerAmmo.mg=2');const prior=h.run('bullets.length');h.run('fireWeapons(player,false,1,true)');assert.equal(h.run('playerAmmo.mg'),0);assert.equal(h.run('bullets.length'),prior+2);h.run('fireWeapons(player,false,1,true)');assert.equal(h.run('bullets.length'),prior+2);report.cadence.push({fps,spentInTwoSeconds:spent})
}
const h=makeContext(1),p=plane(h,'i16',true,new THREE.Vector3(0,100,0),true);h.ctx.player=p;h.ctx.playerPlane='i16';setDirection(h,new THREE.Vector3(0,0,-1));for(let n=0;n<60*90;n++){playerStep(h,1/60);propStep(h,[p],1/60)}assert(Math.abs(p.userData.airspeed*3.6-445)<1);report.levelSpeedKmh=p.userData.airspeed*3.6;
for(const mode of ['cursor','joystick']){const x=makeContext(1),a=plane(x,'i16',true,new THREE.Vector3(0,100,0),true);x.ctx.player=a;x.ctx.playerPlane='i16';x.ctx.controlSettings.mode=mode;x.ctx.joystickInput.x=.8;setDirection(x,new THREE.Vector3(1,.2,-1).normalize());for(let n=0;n<1200;n++){playerStep(x,1/120);propStep(x,[a],1/120)}assert(a.position.toArray().every(Number.isFinite));assert(Math.abs(a.quaternion.length()-1)<1e-7);report.flight.push({mode,speedKmh:a.userData.airspeed*3.6,aoaDegrees:a.userData.aoa*180/Math.PI})}
assert.equal(h.run("gunSoundFor('i16','mg')"),'pv1Gun');report.checks=['Two nose ShKAS barrels: 1800 RPM each, 825m/s, damage16, 850 total ammunition','Cadence, final ammunition pair and empty-magazine silence at 30/60/120 FPS','Full-power level flight settles at 445 km/h; both control modes remain finite and normalized','Piston engine configuration and existing machine-gun sound'];fs.writeFileSync(new URL('i16-v18.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
